In [2]:
import numpy as np

for i in range(20):
    print(int(np.random.uniform(30,60)))

38
40
53
53
43
57
55
58
54
46
47
56
42
48
38
48
38
52
52
54


In [56]:
a = np.array([1,2,3,2,1,2,2,6,7,2,3,1,2,2,3,4,5])

In [61]:
trials = []
starts = np.where(a == 1)[0]
for i,j in enumerate(starts[1:]):
    print(a[starts[i]:j])
    trials.append(a[starts[i]:j])
print(a[j:])
trials.append(a[j:])

[1 2 3 2]
[1 2 2 6 7 2 3]
[1 2 2 3 4 5]


In [69]:
for i,j in enumerate(trials):
    if np.count_nonzero(j == 2) > 2:
        print('Trial',i+1,'is a longer trial')

Trial 2 is a longer trial
